package uz.coder.personallibrary

object GetAllCountryList {

    fun getCategory(): Array<String> = arrayOf(
        "Afganistan",
        "Ålandeilande",
        "Albanië",
        "Algerië",
        "Amerikaanse Samoa",
        "Andorra",
        "Angola",
        "Anguilla",
        "Antarktika",
        "Antigua en Barbuda",
        "Argentinië",
        "Armenië",
        "Aruba",
        "Australië",
        "Azerbeidjan",
        "Bahamas",
        "Bahrein",
        "Bangladesj",
        "Barbados",
        "Belarus",
        "Bulgarye",
        "Burkina Faso",
        "Burundi",
        "Chili",
        "Colombië",
        "Comore",
        "Cookeilande",
        "Costa Rica",
        "Curaçao",
        "Demokratiese Republiek van die Kongo",
        "Guadeloupe",
        "Guam",
        "Guatemala",
        "Guernsey",
        "Guinee",
        "Guinee-Bissau",
        "Guyana",
        "Haïti",
        "Heardeiland en McDonaldeilande",
        "Honduras",
        "Hongarye",
        "Hongkong SAS Sjina",
        "Ierland",
        "Indië",
        "Indonesië",
        "Irak",
        "Iran",
        "Israel",
        "Italië",
        "Ivoorkus",
        "Jamaika",
        "Japan",
        "Jemen",
        "Jersey",
        "Jordanië",
        "Kaaimanseilande",
        "Kaap Verde",
        "Kambodja",
        "Kameroen",
        "Kanada",
        "Karibiese Nederland",
        "Katar",
        "Kazakstan",
        "Mauritanië",
        "Mauritius",
        "Mayotte",
        "Meksiko",
        "Mianmar (Birma)",
        "Mikronesië",
        "Moldowa",
        "Monaco",
        "Mongolië",
        "Montenegro",
        "Montserrat",
        "Mosambiek",
        "Namibië",
        "Nauru",
        "Nederland",
        "Nepal",
        "Nicaragua",
        "Nieu-Kaledonië",
        "Nieu-Seeland",
        "Niger",
        "Nigerië",
        "Niue",
        "Noord-Korea",
        "Noord-Macedonië",
        "Noord-Mariane-eilande",
        "Noorweë",
        "Norfolkeiland",
        "Oekraïne",
        "Oesbekistan",
        "Oman",
        "Oos-Timor",
        "Oostenryk",
        "Pakistan",
        "Palau",
        "Palestynse gebiede",
        "Panama",
        "Papoea-Nieu-Guinee",
        "Paraguay",
        "Peru",
        "Pitcairneilande",
        "Pole",
        "Portugal",
        "Puerto Rico",
        "Réunion",
        "Roemenië",
        "Sint Pierre en Miquelon",
        "Sint Vincent en die Grenadine",
        "Siprus",
        "Sirië",
        "Sjina",
        "Slowakye",
        "Slowenië",
        "Soedan",
        "Somalië",
        "Spanje",
        "Sri Lanka",
        "Suid-Afrika",
        "Suid-Georgië en die Suidelike Sandwicheilande",
        "Suid-Korea",
        "Suid-Soedan",
        "Suriname",
        "Svalbard en Jan Mayen",
        "Swede",
        "Switserland",
        "Tadjikistan",
        "Taiwan",
        "Tanzanië",
        "Thailand",
        "Togo",
        "Tokelau",
        "Tonga",
        "Trinidad en Tobago",
        "Tsjad",
        "Tsjeggië",
        "Uzbekistan"
    )

}